### ISSUE TITLE
各トピックの型を決定する

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/EKF_Localization_learning#5]
各トピックの型を決めてください

**Comment by ximomoi** [comment]
オドメトリ   /nav_msgs/Odometry
IMU          /sensor_msgs/Imu
GPS         /gazebo/model_states　←使わない
　　　　　中身
　　　　　pose:
　　　　　 positon:x,y,z
　　　　　 orientation:x,y,z,w
　　　　　twist:
　　　　　 linear:x,y,z
　　　　　 angular:x,y,z
GPS        /geometry_msgs/Pose2D  ←こっちを使う
                  中身
                 x,y,theta
ノイズ有り /std_msgs/Float64MultiArray
カルマン   /std_msgs/Float64MultiArray

**Comment by Nasupl** [comment]
制御入力としてgeometry_msgs/Twistを利用します

**Comment by Nasupl** [comment]
トピック名についても検討が必要

**Comment by ximomoi** [comment]
GPSはトピックで配信されていないのでAPIを叩くしかないようだ

**Comment by DaikiMaekawa** [comment]
@ximo112 ワールドプラグインを作成し、その中でGazebo APIを叩いてトピックとして配信すればいい。

**Comment by ximomoi** [comment]
@DaikiMaekawa World Pluginの導入について質問なのですが、[$gazebo factory.world]実行時のエラーメッセージでlibfactory.soが必要と言われました。
なので、libfactory.soを含んでいるrpmファイルをダウンロードして、rpm2cpioコマンドよりlibfactory.soのみを展開し /opt/ros/indigo/lib/に入れたのですが解決しませんでした。
どのように対処すればよろしいのでしょうか？
よろしくお願いします。

エラーメッセージ:
Error [Plugin.hh:156] Failed to load plugin libfactory.so: libfactory.so: cannot open shared object file: No such file or directory

**Comment by DaikiMaekawa** [comment]
CATKIN_WS/devel/libの中にlibfactory.soはありますか?

**Comment by ximomoi** [comment]
CATKIN_WS/devel/libの中には無いです、入れて試してみます。

**Comment by DaikiMaekawa** [comment]
そもそもライブラリの生成に失敗しているようですね。 サンプルプログラムをもっとよく見てみてください。

**Comment by ximomoi** [comment]
/gazebo_msgs/model_statesよりモデルの絶対位置の配信を確認、これを利用

**Comment by ximomoi** [comment]
トピックが決まり、各ノードが作成されので閉じます。
